### ISSUE TITLE
Missing copyright attribution

### ISSUE THREAD

**Issue by ifreund** [Natchuz/wmoon#2]
e8fa2552512518b373926b777ebda656a0eb32a3 removed the copyright notices from all of the code. I find this unacceptable, as this code is all copyright the river developers. To be clear I have nothing against forks of river, removing other people's copyright from source code is never ok though.

**Comment by Natchuz** [comment]
Hello,
first of all, I would like to apologise for this situation. I didn't realised I violated GPL license (because that's where copyright preservation requirement come from I suppose?) until now. I didn't do that on purpose, it just came purely from my lack of full understanding of this license, (I've once worked on a GPLv3 project and never seen any license headers or copyright notice), and I never intended to discredit work of original developers. (Hey, I did put _some_ credit in README file (although non-copyright one))

I'll revert this change once I have access to my computer, in about a week. However, since I've done it just for aesthetics reasons, I would prefer to preserve only a copyright notice at the top of a file and further point to LICENSE file (which is supposedly ok as per GPL terms). If you still insist on reverting entire commit (with full license notice), I will do it. 
Once again, I'm sorry this happened. 

PS. Am I required to also put original copyright notice in the new files created by me?

**Comment by ifreund** [comment]
Hey! I've done some more reading of my own on this topic and it seems that these days copyright law is such that no explicit copyright notice is required from a legal standpoint and the GPL license headers the FSF recommends are more of a "best practice" thing to make it easier to keep track of what code is copyrighted to whom as opposed to a hard requirement.

Anyhow, it seems that legally your dropping of the headers is fine so I'll close this issue. Sorry for the uninformed knee-jerk reaction and best of luck with your project!
